# Generated by Django 3.0.8 on 2020-07-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 11, 11, 0, 287767), verbose_name='Date Created'),
        ),
    ]
